version: '3'

services:

  mysql:
    image: mysql:5.7
    ports:
      # altere o número antes de do ':' caso a porta já esteja sendo utilizada em seu sistema
      - 3306:3306
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: 1q2w3e4r

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      # altere o número antes de do ':' caso a porta já esteja sendo utilizada em seu sistema
      - 80:80
    volumes:
      # Os arquivos do Wordpress serão instalados na pasta /wordpress, seu tema será colocado na pasta /wordpress/wp-content/themes para desenvolvimento
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: 1q2w3e4r
      WORDPRESS_DB_NAME: wordpress